baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Tech Blog'
theme = "hugo-blog-awesome"
cleanDestinationDir = true

[[params.socialIcons]]
name = "github"
url = "https://github.com/krafthem/blog"

[params]
  goToTop = true


